// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Laborator1.Migrations
{
    [DbContext(typeof(TeatruDbContext))]
    partial class TeatruDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Spectacol", b =>
                {
                    b.Property<int>("IdS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdS"));

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Denumire");

                    b.Property<string>("Descriere")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Descriere");

                    b.Property<int>("IdT")
                        .HasColumnType("int")
                        .HasColumnName("IdT");

                    b.HasKey("IdS");

                    b.HasIndex("IdT");

                    b.ToTable("Spectacole");
                });

            modelBuilder.Entity("TeatruNational", b =>
                {
                    b.Property<int>("IdT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdT"));

                    b.Property<int>("AnInfiintare")
                        .HasColumnType("int")
                        .HasColumnName("AnInfiintare");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Denumire");

                    b.Property<string>("Oras")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Oras");

                    b.HasKey("IdT");

                    b.HasIndex("Denumire")
                        .IsUnique();

                    b.ToTable("TeatruNational");
                });

            modelBuilder.Entity("Spectacol", b =>
                {
                    b.HasOne("TeatruNational", "TeatruNational")
                        .WithMany("Spectacole")
                        .HasForeignKey("IdT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeatruNational");
                });

            modelBuilder.Entity("TeatruNational", b =>
                {
                    b.Navigation("Spectacole");
                });
#pragma warning restore 612, 618
        }
    }
}
